import { images, type ImageName } from "@/lib/images.generated";

type Props = {
  name: ImageName;
  alt: string;
  sizes: string;
  className?: string;
  priority?: boolean;
};

/** Responsive WebP image generated by `npm run images`. Width/height prevent layout shift. */
export function Picture({ name, alt, sizes, className, priority }: Props) {
  const meta = images[name];
  const largest = meta.widths[meta.widths.length - 1];
  const srcSet = meta.widths.map((width) => `/images/${name}-${width}.webp ${width}w`).join(", ");
  return (
    <img
      className={className}
      src={`/images/${name}-${largest}.webp`}
      srcSet={srcSet}
      sizes={sizes}
      width={meta.width}
      height={meta.height}
      alt={alt}
      loading={priority ? "eager" : "lazy"}
      decoding={priority ? "sync" : "async"}
      fetchPriority={priority ? "high" : undefined}
    />
  );
}

export const SIZES = {
  half: "(max-width: 780px) 100vw, 50vw",
  third: "(max-width: 780px) 100vw, 33vw",
  twoThirds: "(max-width: 780px) 100vw, 66vw",
  full: "100vw",
} as const;
