// Generated by scripts/optimize-images.py — do not edit by hand.
export const images = {
  "agri-logistics": { width: 1774, height: 887, widths: [640, 960, 1440, 1774] },
  "community-tourism": { width: 1448, height: 1086, widths: [640, 960, 1448] },
  "cooperative-leadership": { width: 1448, height: 1086, widths: [640, 960, 1448] },
  "green-mobility": { width: 1672, height: 941, widths: [640, 960, 1440, 1672] },
  "hero-mobility": { width: 2048, height: 768, widths: [640, 960, 1440, 1920] },
  "pilgrimage-mobility": { width: 1672, height: 941, widths: [640, 960, 1440, 1672] },
} as const;

export type ImageName = keyof typeof images;
