"""Generate responsive WebP images, icons and the social card from the source masters.

Masters live in assets/ (not deployed). Output goes to public/ and lib/images.generated.ts.
Run after adding or replacing an image:  npm run images   (requires Python 3 + Pillow)
"""
from pathlib import Path
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "assets" / "img"
OUT = ROOT / "public" / "images"
WIDTHS = [640, 960, 1440, 1920]
OUT.mkdir(parents=True, exist_ok=True)

manifest = {}
for master in sorted((SRC / "generated").glob("*.jpg")):
    image = Image.open(master).convert("RGB")
    widths = [w for w in WIDTHS if w < image.width * 0.9] + [min(image.width, WIDTHS[-1])]
    for width in sorted(set(widths)):
        height = round(image.height * width / image.width)
        image.resize((width, height), Image.LANCZOS).save(OUT / f"{master.stem}-{width}.webp", "WEBP", quality=72, method=6)
    manifest[master.stem] = {"width": image.width, "height": image.height, "widths": sorted(set(widths))}

# Social sharing card (1200x630 JPEG — the most widely supported og:image format)
hero = Image.open(SRC / "generated" / "hero-mobility.jpg").convert("RGB")
scale = 630 / hero.height if hero.width / hero.height > 1200 / 630 else 1200 / hero.width
card = hero.resize((round(hero.width * scale), round(hero.height * scale)), Image.LANCZOS)
left, top = (card.width - 1200) // 2, (card.height - 630) // 2
card.crop((left, top, left + 1200, top + 630)).save(OUT / "og-cover.jpg", "JPEG", quality=82, optimize=True, progressive=True)

# Logo at 2x its largest display size (57px)
logo = Image.open(SRC / "brand" / "nftci-logo.png").convert("RGBA")
logo.resize((120, round(logo.height * 120 / logo.width)), Image.LANCZOS).save(OUT / "nftci-logo.webp", "WEBP", quality=90, method=6)

# App icons (Next.js picks these up from app/): the NFTCI wheel cut from the official logo.
# The full emblem's Hindi text and "NFTCI" label are unreadable at favicon sizes, so only the wheel is used.
flat = Image.new("RGBA", logo.size, "white")
flat.alpha_composite(logo)
ImageDraw.Draw(flat).rectangle([0, 119, logo.width, logo.height], fill="white")  # remove the NFTCI label
cx, cy, r = 81, 81, 56  # wheel centre and radius inside the black ring, in logo pixels
wheel = flat.crop((cx - r, cy - r, cx + r, cy + r)).resize((512, 512), Image.LANCZOS)
mask = Image.new("L", (512, 512), 0)
ImageDraw.Draw(mask).ellipse([0, 0, 511, 511], fill=255)
disc = Image.new("RGBA", (512, 512), (0, 0, 0, 0))
disc.paste(wheel, (0, 0), mask)
disc.save(ROOT / "app" / "favicon.ico", sizes=[(16, 16), (32, 32), (48, 48)])
disc.resize((192, 192), Image.LANCZOS).save(ROOT / "app" / "icon.png", optimize=True)
apple = Image.new("RGBA", (180, 180), (255, 255, 255, 255))
apple.alpha_composite(disc.resize((156, 156), Image.LANCZOS), (12, 12))
apple.convert("RGB").save(ROOT / "app" / "apple-icon.png", optimize=True)

lines = ["// Generated by scripts/optimize-images.py — do not edit by hand.", "export const images = {"]
for name, meta in manifest.items():
    lines.append(f'  "{name}": {{ width: {meta["width"]}, height: {meta["height"]}, widths: {meta["widths"]} }},')
lines += ["} as const;", "", "export type ImageName = keyof typeof images;", ""]
(ROOT / "lib").mkdir(exist_ok=True)
(ROOT / "lib" / "images.generated.ts").write_text("\n".join(lines))
print("ok", {k: v["widths"] for k, v in manifest.items()})
